### ISSUE TITLE
ファイル名のルールの統一

### ISSUE THREAD

**Issue by piro0919** [LeeDDHH/react-async#1]
ファイル名にルールが統一されていないように感じました。

以下のようなルールを決めてはいかがでしょうか。

- index.jsを除くcontainers及びcomponentsはUpper Camel Case
- その他のファイルはLower Camel Case

**Comment by LeeDDHH** [comment]
fetchData.js
appReducer.js
へ変更しました。

※Snake caseからLower Camel Caseへ変更

**Comment by piro0919** [comment]
https://github.com/LeeDDHH/react-async/blob/master/src/Store.js

こちらも修正よろしくお願いします。
