### ISSUE TITLE
Prettierの導入

### ISSUE THREAD

**Issue by piro0919** [LeeDDHH/react-async#2]
無駄な空行や、必要なはずの改行が抜けている箇所が散見されます。

Prettierの導入をご検討頂きたく思います。

**Comment by LeeDDHH** [comment]
Prettierを導入し、フォーマットを書けました。
たしかに、無駄な行はスッキリしました。

※導入：npm install --save-dev --save-exact prettier
※package.jsonにscript設定

**Comment by piro0919** [comment]
【補足】

VisualStudioCodeを使用していましたら、パッケージではなく、追加プラグインの方がオススメです。

https://github.com/prettier/prettier-vscode

（`--save-exact`のオプションを初めて知りました）
