### ISSUE TITLE
componentWillMountを使用しない

### ISSUE THREAD

**Issue by piro0919** [LeeDDHH/react-async#3]
詳細は以下に記載してありますので、ご確認して頂きたく思います。
https://reactjs.org/docs/react-component.html#unsafe_componentwillmount

`fetch`などの処理は`componentDidMount`に記述して頂きたく思います。

**Comment by LeeDDHH** [comment]
ドキュメントを一読し、
componentDidMountへ変更しました。

※「fetchのような非同期的な処理」と「DOMに関わる初期化処理」をする際に`componentDidMount`で行う認識でよろしいでしょうか？
[参考1](https://daveceddia.com/where-fetch-data-componentwillmount-vs-componentdidmount/)
[参考2](https://qiita.com/koba04/items/66e9c5be8f2e31f28461)

※「サーバーと同期してレンダリングする場合」は`componentWillMount`を使って、
「ユーザーの操作でサーバーから追加でレンダリングする必要がある場合」には`componentWillUpdate`を使う認識でよろしいでしょうか？

**Comment by piro0919** [comment]
> ※「fetchのような非同期的な処理」と「DOMに関わる初期化処理」をする際にcomponentDidMountで行う認識でよろしいでしょうか？

「fetchのような非同期的な処理」については、認識に相違ないです。
「DOMに関わる初期化処理」については、申し訳ないのですが、ちょっと意味がわかりませんでした…。

> ※「サーバーと同期してレンダリングする場合」はcomponentWillMountを使って、
> 「ユーザーの操作でサーバーから追加でレンダリングする必要がある場合」にはcomponentWillUpdateを使う認識でよろしいでしょうか？

こちらについては、認識が誤っています。
以下のドキュメントをご参考ください。

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

Reactの仕様はメジャーバージョンアップとともに変わる可能性がとても高いので、古いドキュメントはあまり参考になりません。
過去には正しい情報であったとしても、今現在は間違っている情報も非常に多くあります。

まずは公式ドキュメントを把握することが、理解への一番早いアプローチになるかと思います。
（自分もまだあやふやなところが多いのですが…）
